Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 0 -d 0 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 0 -d 1 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 0 -d 2 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 0 -d 3 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 0 -d 4
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 1 -d 0 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 1 -d 1 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 1 -d 2 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 1 -d 3 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 1 -d 4
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 2 -d 0 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 2 -d 1 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 2 -d 2 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 2 -d 3 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 2 -d 4
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 3 -d 0 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 3 -d 1 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 3 -d 2 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 3 -d 3 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 3 -d 4 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 4 -d 0 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 4 -d 1 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 4 -d 2 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 4 -d 3 
Schemes/Maxwell2D/Maxwell2D --exact -f sphere/ --logfile-prefix -t 4e-5 -m 4 -d 4 
